### ISSUE TITLE
Empty examples

### ISSUE THREAD

**Issue by borondics** [alchem0x2A/py-wdf-reader#24]
The example .wdf files are empty. I would like to use them for some testing but I don't have the instrument... Could you update them?

**Comment by alchem0x2A** [comment]
Hi

Thanks for the interest in the package! Yes the files are only placeholders since the full-size spectra are around 40 MB in total and I don't have a data storage plan for git-lfs ...

Please check the information in [this section](https://github.com/alchem0x2A/py-wdf-reader#head-version-via-git--pip), basically the testing files are stored with the [github release](https://github.com/alchem0x2A/py-wdf-reader/releases/download/binary/spectra_files.zip) and you just simply overwrite the files inside the `examples/`

**Comment by borondics** [comment]
Thanks for the quick reply! I got the files and now they work fine.
