### ISSUE TITLE
WDFReader Error: "ValueError: WMAP Xpad is not same as in ORGN!" 

### ISSUE THREAD

**Issue by JLevermore** [alchem0x2A/py-wdf-reader#29]
Hi, 

I am trying to open a streamline scan obtained using a Renishaw Raman microscope using your package. When attempting to open the ".wdf" file the following error occurs: ValueError("WMAP Xpad is not same as in ORGN!"). Have you come across this error before? And do you know how I go about resolving it? 

Regards, 

Joseph

**Comment by alchem0x2A** [comment]
Hi Joseph,

Is it possible to send me the file that you used for debugging? The thing is I’ve only obtained data using the StreamLine HR previously (the renishaw instrument I don’t own). Probably there are some different implementations in original Streamline mode.

In brief I just checked the position information from WMAP and ORGN blocks, it could be that they are slightly different. If indeed there is such issue, I will update a version which shows a warning instead of throwing exceptions.

Best wishes
Tian

**Comment by JLevermore** [comment]
HI Tian,

Thank you for your prompt response and please see attached the .wdf file I am attempting to open. Just out of interest I have been trying to improve my python skills for accessing differing data files, I was wondering whether you know of any books or material you could recommend.

Regards,

Joseph Levermore

On 4 Sep 2020, at 13:26, T.Tian <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Joseph,

Is it possible to send me the file that you used for debugging? The thing is I’ve only obtained data using the StreamLine HR previously (the renishaw instrument I don’t own). Probably there are some different implementations in original Streamline mode.

In brief I just checked the position information from WMAP and ORGN blocks, it could be that they are slightly different. If indeed there is such issue, I will update a version which shows a warning instead of throwing exceptions.

Best wishes
Tian

**Comment by alchem0x2A** [comment]
Hi Joseph

Much appreciated for your response. Unfortunately I couldn’t see the attachments in the issues, possibly they were just eaten by the Github octopus. Could you maybe post a link to that file (i.e. via dropbox) to my working email? (tian.tian@chem.ethz.ch <mailto:tian.tian@chem.ethz.ch>) you can set expiration of 12 h etc.

For the APIs to read the data of the wdf file I heavily rely on the codes by Gwyddion (https://sourceforge.net/p/gwyddion/code/HEAD/tree/trunk/gwyddion/modules/file/renishaw.c <https://sourceforge.net/p/gwyddion/code/HEAD/tree/trunk/gwyddion/modules/file/renishaw.c>). Many of the C-like chunks can be easily converted to a python-flavored codes.

Best
Tian

**Comment by alchem0x2A** [comment]
Hi

The bug is caused because the previous code cannot handle XY-scan that starts with y-direction first, which appears in your testing wdf file.

PR #30 has been created for your issue. You could pull the commit (437c097) to check if the fix works for your other files that taken using the Streamline method. A quick previous of your testing raw data now looks as follows
![mapping_streamline](https://user-images.githubusercontent.com/6829706/92257504-9eed0680-eed5-11ea-9f30-80dbf2441917.png)

If that works, I'll merge the revisions in the master branch :)
