### ISSUE TITLE
Move away from GPL licence

### ISSUE THREAD

**Issue by AlexHenderson** [alchem0x2A/py-wdf-reader#42]
Is it possible to move away from the GPL licence? This is a viral licence in that any project using your code must change to a GPL licence too. This means I can't use it in my projects. 
Thanks

**Comment by alchem0x2A** [comment]
Hi @AlexHenderson I believe I chose the package to be GPL because many codes of my current logic are referred from your Matlab code on zenodo (which is GPLv3) :)

Since I don't actually import your matlab code in this package (to my best knowledge), I think it's ok to switch to more flexible licenses. I appreciate if you could take a look and let me know if that's ok for you? Come to my mind are BSD or MIT licenses but I'm open to other suggestions.

**Comment by AlexHenderson** [comment]
Hi, 

 

D’oh! Well I’ll re-licence mine to MIT (which I think is allowed). 

Not really sure why I picked GPL in the first place. A bit naive in those days…

 

IANAL, but I believe MIT and BSD-2 are compatible, and BSD-3 only needs a statement saying you’re not endorsing your code with the code being ‘imported’. Not sure about BSD-4. (https://fossa.com/blog/open-source-software-licenses-101-bsd-3-clause-license/)

 

Thanks for getting back to me, and I hope to be able to use your code. 

 

Alex
